local skills = 
{
    skill_1 = {
        title = "Intimidating I",
        desc = "You gain sanity at maximum fear.",
        icon = "skill_intimidating_1",
        group = "",
        tags = {},
        pos = {0, 0},
    },
    skill_2 = {
        title = "Intimidating II",
        desc = "You deal much more damage at maximum fear",
        icon = "skill_intimidating_1",
        group = "",
        tags = {},
        pos = {0, 0},
    },
    skill_3 = {
        title = "Intimidating III",
        desc = "You gain a small amount of fear when you deal damage",
        icon = "skill_intimidating_1",
        group = "",
        tags = {},
        pos = {0, 0},
    },
    skill_4 = {
        title = "Intimidating IV",
        desc = "You gain a small amount of fear when you deal damage",
        icon = "skill_intimidating_1",
        group = "",
        tags = {},
        pos = {0, 0},
    },
    skill_5 = {
        title = "Intimidating V",
        desc = "Fear drains slower",
        icon = "skill_intimidating_1",
        group = "",
        tags = {},
        pos = {0, 0},
    },
    skill_6 = {
        title = "Intimidating VI",
        desc = "Charlie will not attack you at maximum fear",
        icon = "skill_intimidating_1",
        group = "",
        tags = {},
        pos = {0, 0},
    },
    skill_7 = {
        title = "Intimidating Mastery I",
        desc = "You do not lose fear while scaring nearby survivors",
        icon = "skill_intimidating_1",
        group = "",
        tags = {},
        pos = {0, 0},
    },
    skill_8 = {
        title = "Intimidating Mastery II",
        desc = "You scare nearby creatures",
        icon = "skill_intimidating_1",
        group = "",
        tags = {},
        pos = {0, 0},
    },
    skill_9 = {
        title = "Unintimidating",
        desc = "Makes Luke even less intimidating",
        icon = "wilson_torch_time_1",
        group = "",
        tags = {},
        pos = {0, 0},
    },
    skill_10 = {
        title = "Safe Aura",
        desc = "Luke gains reduced fear from kills",
        icon = "wilson_torch_time_2",
        group = "",
        tags = {},
        pos = {0, 0},
    },
}
return skills